packages:
  - 'packages/components/*'
  - packages/ohvue
  - packages/composables
  - packages/utils
  - packages/storybook

catalog:
  unplugin-external: ^0.1.0-beta.2
  unplugin-vue: ^5.2
  vite: ^6
  vite-plugin-dts: ^4.5
  vue: ^3.5
  '@storybook/vue3': ^8.5
